Repository umccr/data-portal-apis, pull requests merged in 2021-11, with the labels that each got.

#350 Fixed migration order refactor side effect
  data_portal/management/commands/repopulatetable.py
  data_portal/models/batch.py
  data_portal/models/batchrun.py
  data_portal/models/configuration.py
  data_portal/models/fastqlistrow.py
  data_portal/models/gdsfile.py
  data_portal/models/labmetadata.py
  data_portal/models/libraryrun.py
  data_portal/models/limsrow.py
  data_portal/models/report.py
  data_portal/models/s3lims.py
  data_portal/models/s3object.py
  data_portal/models/sequence.py
  data_portal/models/sequencerun.py
  data_portal/models/tests/test_fastqlistrow.py
  data_portal/models/tests/test_gdsfile.py
  data_portal/models/tests/test_libraryrun.py
  data_portal/models/tests/test_s3object.py
  data_portal/models/tests/test_sequence.py
  data_portal/models/tests/test_sequencerun.py
  data_portal/models/tests/test_utils.py
  data_portal/models/tests/test_workflow.py
  data_portal/models/utils.py
  data_portal/models/workflow.py
  data_portal/tests/factories.py
  data_portal/viewsets/bucket.py
  data_portal/viewsets/fastqlistrow.py
  data_portal/viewsets/gdsfile.py
  data_portal/viewsets/labmetadata.py
  data_portal/viewsets/libraryrun.py
  data_portal/viewsets/limsrow.py
  data_portal/viewsets/presignedurl.py
  data_portal/viewsets/report.py
  data_portal/viewsets/s3object.py
  data_portal/viewsets/sequence.py
  data_portal/viewsets/sequencerun.py
  data_portal/viewsets/subject.py
  data_portal/viewsets/tests/__init__.py
  data_portal/viewsets/tests/test_libraryrun.py
  data_portal/viewsets/tests/test_sequence.py
  data_portal/viewsets/utils.py
  data_portal/viewsets/workflow.py
  data_processors/s3/services.py
  data_processors/s3/tests/test_s3_event.py
Labels: refactor

#349 Start adding source/type filters to look for FFPE/FF
  data_portal/s3_object_search.py
Labels: change-request

#352 Restructure gds output and intermediate paths
  data_portal/migrations/0037_workflow_portal_run_id.py
  data_portal/models/workflow.py
  data_portal/tests/factories.py
  data_processors/pipeline/domain/tests/test_workflow.py
  data_processors/pipeline/domain/workflow.py
  data_processors/pipeline/lambdas/bcl_convert.py
  data_processors/pipeline/lambdas/dragen_tso_ctdna.py
  data_processors/pipeline/lambdas/dragen_wgs_qc.py
  data_processors/pipeline/lambdas/dragen_wts.py
  data_processors/pipeline/lambdas/orchestrator.py
  data_processors/pipeline/lambdas/tests/test_dragen_wgs_qc.py
  data_processors/pipeline/lambdas/tests/test_dragen_wts.py
  data_processors/pipeline/lambdas/tests/test_notification.py
  data_processors/pipeline/lambdas/tests/test_orchestrator.py
  data_processors/pipeline/lambdas/tests/test_sqs_iap_event.py
  data_processors/pipeline/lambdas/tumor_normal.py
  data_processors/pipeline/lambdas/workflow_update.py
  data_processors/pipeline/orchestration/dragen_tso_ctdna_step.py
  data_processors/pipeline/orchestration/dragen_wgs_qc_step.py
  data_processors/pipeline/orchestration/dragen_wts_step.py
  data_processors/pipeline/orchestration/tests/test_dragen_tso_ctdna_step.py
  data_processors/pipeline/orchestration/tests/test_dragen_wgs_qc_step.py
  data_processors/pipeline/orchestration/tests/test_dragen_wts_step.py
  data_processors/pipeline/orchestration/tumor_normal_step.py
  data_processors/pipeline/services/notification_srv.py
  data_processors/pipeline/services/workflow_srv.py
  data_processors/pipeline/tools/liborca.py
  utils/libdt.py
Labels: feature, refactor, change-request

#357 Merged LibraryRun SampleSheet no lane fix from main to dev
  data_processors/pipeline/services/library_run_srv.py
  data_processors/pipeline/services/tests/test_library_run_srv.py
  data_processors/pipeline/tools/liborca.py
  data_processors/pipeline/tools/tests/test_liborca.py
Labels: critical, fix

#360 Populate LibraryRun upon SequenceRun status PendingAnalysis (#356)
  data_processors/pipeline/lambdas/sqs_iap_event.py
Labels: fix

#361 Renamed service module
  data_processors/pipeline/domain/pairing.py
  data_processors/pipeline/domain/tests/test_pairing.py
  data_processors/pipeline/lambdas/bcl_convert.py
  data_processors/pipeline/lambdas/dragen_tso_ctdna.py
  data_processors/pipeline/lambdas/dragen_wgs_qc.py
  data_processors/pipeline/lambdas/dragen_wts.py
  data_processors/pipeline/lambdas/sqs_iap_event.py
  data_processors/pipeline/lambdas/tests/test_bcl_convert.py
  data_processors/pipeline/lambdas/tests/test_sqs_iap_event.py
  data_processors/pipeline/lambdas/tumor_normal.py
  data_processors/pipeline/orchestration/tests/test_tumor_normal_step.py
  data_processors/pipeline/services/libraryrun_srv.py
  data_processors/pipeline/services/sequencerun_srv.py
  data_processors/pipeline/services/tests/test_libraryrun_srv.py
  data_processors/pipeline/services/tests/test_metadata_srv.py
  data_processors/pipeline/services/tests/test_notification_srv.py
  data_processors/pipeline/services/tests/test_sequencerun_srv.py
Labels: refactor

#362 Added libraryrun lambda
  data_processors/pipeline/lambdas/libraryrun.py
  data_processors/pipeline/lambdas/tests/test_libraryrun.py
  data_processors/pipeline/services/libraryrun_srv.py
  serverless.yml
Labels: feature

#351 Refactor HTTP Query Params
  data_portal/models/base.py
  data_portal/models/fastqlistrow.py
  data_portal/models/labmetadata.py
  data_portal/models/libraryrun.py
  data_portal/models/limsrow.py
  data_portal/models/report.py
  data_portal/models/sequence.py
  data_portal/models/sequencerun.py
  data_portal/models/tests/test_base.py
  data_portal/models/tests/test_labmetadata.py
  data_portal/models/tests/test_libraryrun.py
  data_portal/models/tests/test_utils.py
  data_portal/models/tests/test_workflow.py
  data_portal/models/utils.py
  data_portal/models/workflow.py
  data_portal/pagination.py
  data_portal/urls.py
  data_portal/viewsets/fastqlistrow.py
  data_portal/viewsets/labmetadata.py
  data_portal/viewsets/libraryrun.py
  data_portal/viewsets/limsrow.py
  data_portal/viewsets/report.py
  data_portal/viewsets/sequence.py
  data_portal/viewsets/sequencerun.py
  data_portal/viewsets/tests/test_fastqlistrow.py
  data_portal/viewsets/tests/test_labmetadata.py
  data_portal/viewsets/tests/test_libraryrun.py
  data_portal/viewsets/tests/test_reports.py
  data_portal/viewsets/tests/test_sequence.py
  data_portal/viewsets/tests/test_sequencerun.py
  data_portal/viewsets/tests/test_workflow.py
  data_portal/viewsets/workflow.py
Labels: refactor

#364 Added Subject result summary from GDS (#359)
  data_portal/models/gdsfile.py
  data_portal/viewsets/subject.py
Labels: feature

#367 Bumped dependencies
  package.json
  requirements-dev.txt
  requirements-test.txt
  requirements.txt
  yarn.lock
Labels: dependencies

#368 Squashed migrations 0001 to 0037 (#342)
  data_portal/migrations/0001_squashed_0037_workflow_portal_run_id.py
  data_portal/migrations/0012_auto_20200123_0655.py
Labels: refactor

#369 Fixed bcl_convert notification display name
  data_processors/pipeline/services/notification_srv.py
  data_processors/pipeline/services/tests/test_notification_srv.py
Labels: fix

#370 Improved library run linking impl
  data_portal/tests/factories.py
  data_processors/pipeline/services/libraryrun_srv.py
  data_processors/pipeline/services/tests/test_libraryrun_srv.py
Labels: fix
