Repository umccr/data-portal-apis, pull requests merged in 2021-09, with the labels that each got.

#288 Implemented pairing domain model
  data_portal/models.py
  data_portal/urls.py
  data_portal/views.py
  data_portal/viewsets.py
  data_processors/pipeline/domain/pairing.py
  data_processors/pipeline/domain/tests/test_pairing.py
  data_processors/pipeline/orchestration/tumor_normal_step.py
  data_processors/pipeline/services/metadata_srv.py
  data_processors/pipeline/services/sequence_srv.py
  data_processors/pipeline/services/workflow_srv.py
  swagger/swagger.json
  tn_debug.py
Labels: feature

#294 Add POST to presign endpoint
  data_portal/viewsets.py
  swagger/swagger.json
  utils/gds.py
Labels: feature

#300 Refactored GDS event processing (#298)
  data_portal/management/commands/addreport.py
  data_portal/management/commands/gdscrawler.py
  data_portal/management/commands/syncmeta.py
  data_processors/const.py
  data_processors/gds/__init__.py
  data_processors/gds/lambdas/__init__.py
  data_processors/gds/lambdas/gds_event.py
  data_processors/gds/services.py
  data_processors/gds/tests/__init__.py
  data_processors/gds/tests/case.py
  data_processors/gds/tests/test_gds_event.py
  data_processors/pipeline/domain/workflow.py
  data_processors/pipeline/lambdas/sqs_iap_event.py
  data_processors/pipeline/lambdas/tests/test_sqs_iap_event.py
  data_processors/pipeline/services/gds_srv.py
  data_processors/reports/services.py
  data_processors/reports/tests/test_report.py
  data_processors/s3/helper.py
  data_processors/s3/lambdas/s3_event.py
  data_processors/s3/services.py
  data_processors/s3/tests/test_helper.py
  data_processors/s3/tests/test_s3_event.py
  data_processors/test_const.py
  serverless.yml
  utils/ica.py
  utils/libs3.py
  utils/tests/test_ica.py
Labels: refactor, change-request

#302 Filter pairing of run tumors that are an intersection of subject tumors
  data_processors/pipeline/orchestration/tumor_normal_step.py
Labels: fix

#305 Fastq API endpoint can be queried by project owner
  data_portal/models.py
  data_portal/tests/test_fastq_list_row.py
  data_portal/viewsets.py
  data_processors/pipeline/services/fastq_srv.py
Labels: change-request

#306 Added `project_owner` input filter in fastq lambda
  data_processors/pipeline/lambdas/fastq.py
  data_processors/pipeline/lambdas/tests/test_fastq.py
Labels: change-request
