Repository umccr/data-portal-apis, pull requests merged in 2021-10, with the labels that each got.

#315 library run api implementation
  data_portal/models.py
  data_portal/serializers.py
  data_portal/tests/test_library_run.py
  data_portal/urls.py
  data_portal/viewsets.py
Labels: feature

#320 Implement sequence api
  data_portal/models.py
  data_portal/serializers.py
  data_portal/tests/test_sequence.py
  data_portal/urls.py
  data_portal/viewsets.py
Labels: feature

#327 Implemented linking between Workflow and LibraryRun (#325)
  data_portal/migrations/0036_libraryrun_workflows.py
  data_portal/models.py
  data_portal/tests/factories.py
  data_processors/pipeline/domain/workflow.py
  data_processors/pipeline/lambdas/dragen_tso_ctdna.py
  data_processors/pipeline/lambdas/dragen_wgs_qc.py
  data_processors/pipeline/lambdas/dragen_wts.py
  data_processors/pipeline/lambdas/tests/test_dragen_tso_ctdna.py
  data_processors/pipeline/lambdas/tests/test_dragen_wgs_qc.py
  data_processors/pipeline/lambdas/tests/test_dragen_wts.py
  data_processors/pipeline/lambdas/tests/test_notification.py
  data_processors/pipeline/lambdas/tests/test_tumor_normal.py
  data_processors/pipeline/lambdas/tumor_normal.py
  data_processors/pipeline/lambdas/workflow_update.py
  data_processors/pipeline/orchestration/tests/test_tumor_normal_step.py
  data_processors/pipeline/services/library_run_srv.py
  data_processors/pipeline/services/metadata_srv.py
  data_processors/pipeline/services/notification_srv.py
  data_processors/pipeline/services/tests/test_metadata_srv.py
  data_processors/pipeline/services/tests/test_notification_srv.py
  data_processors/pipeline/services/workflow_srv.py
Labels: feature, change-request

#336 link BCL_CONVERT with libraryRun
  data_processors/pipeline/lambdas/bcl_convert.py
  data_processors/pipeline/lambdas/tests/test_bcl_convert.py
  data_processors/pipeline/services/library_run_srv.py
  data_processors/pipeline/tools/liborca.py
Labels: change-request
