Repository umccr/data-portal-apis, pull requests merged in 2022-08, with the labels that each got.

#488 add manops viewset
  data_portal/urls.py
  data_portal/viewsets/manops.py
  data_portal/viewsets/tests/test_manops.py
  data_processors/pipeline/domain/manops.py
  data_processors/pipeline/domain/tests/test_manops.py
  data_processors/pipeline/services/tests/test_workflow_srv.py
  data_processors/pipeline/services/workflow_srv.py
  serverless.yml
Labels: feature

#489 update manops domain
  data_portal/viewsets/manops.py
  data_processors/pipeline/domain/manops.py
  data_processors/pipeline/domain/tests/test_manops.py
  data_processors/pipeline/services/tests/test_workflow_srv.py
  data_processors/pipeline/services/workflow_srv.py
Labels: feature

#490 Remove 'wgs' regex for GPL reports on GDS
  data_portal/models/gdsfile.py
Labels: change request, fix

#491 Added Portal Athena CLI use case
  docs/athena/LibraryRun.sql
  docs/athena/README.md
  docs/athena/README_CLI.md
  docs/athena/athena_cli_start.json
  docs/athena/athena_cli_start.sh
  docs/athena/demo.sql
  docs/athena/fastq.sql
  docs/athena/img/athena7.png
  docs/athena/pairing.sql
  docs/athena/pipeline.sql
  docs/athena/stats.sql
Labels: documentation

#493 Added Portal ICA Pipeline ENS subscription doc
  docs/pipeline/ica_v1_event/ENS_BSSH.md
  docs/pipeline/ica_v1_event/ENS_GDS.md
  docs/pipeline/ica_v1_event/ENS_WES.md
  docs/pipeline/ica_v1_event/README.md
  docs/pipeline/ica_v1_event/expr.js
Labels: documentation

#494 Fixed duplicate tumor normal trigger in concurrent Sequencing
  data_processors/pipeline/orchestration/tests/test_tumor_normal_step.py
  data_processors/pipeline/orchestration/tumor_normal_step.py
Labels: fix

#495 Added transcriptome `dragen_wts` Lambda entrypoint
  serverless.yml
Labels: change request

#496 Refactored liborca `get_files_from_gds_by_suffix` to libica.app.gds
  data_processors/pipeline/tools/liborca.py
  data_processors/pipeline/tools/tests/test_liborca.py
Labels: refactor

#497 Refactored with tooling from libumccr 0.3.0
  data_portal/viewsets/labmetadata.py
  data_processors/pipeline/domain/manops.py
  data_processors/pipeline/domain/somalier.py
  data_processors/pipeline/lambdas/fastq_list_row.py
  data_processors/pipeline/orchestration/google_lims_update_step.py
  data_processors/pipeline/services/libraryrun_srv.py
  data_processors/pipeline/tools/liborca.py
  data_processors/pipeline/tools/libregex.py
  requirements.txt
Labels: refactor

#498 Bumped dependencies
  package.json
  requirements-test.txt
  requirements.txt
  yarn.lock
Labels: dependencies
