Repository umccr/data-portal-apis, pull requests merged in 2022-05, with the labels that each got.

#455 Added GPL Report query to Subject view
  data_portal/models/s3object.py
Labels: feature

#459 Feature/somalier extract and check
  data_portal/viewsets/somalier_check.py
  data_processors/pipeline/domain/config.py
  data_processors/pipeline/domain/somalier_check.py
  data_processors/pipeline/lambdas/orchestrator.py
  data_processors/pipeline/lambdas/somalier_check.py
  data_processors/pipeline/lambdas/somalier_extract.py
  data_processors/pipeline/lambdas/tests/test_somalier_check.py
  data_processors/pipeline/lambdas/tests/test_somalier_extract.py
  data_processors/pipeline/orchestration/somalier_extract_step.py
  data_processors/pipeline/orchestration/tests/test_somalier_extract_step.py
  data_processors/pipeline/services/somalier_check_srv.py
  data_processors/pipeline/tools/liborca.py
  data_processors/pipeline/tools/tests/test_liborca.py
Labels: feature, epic

#460 Improved Somalier Holmes pipeline integration
  data_portal/urls.py
  data_portal/viewsets/somalier.py
  data_portal/viewsets/somalier_check.py
  data_processors/pipeline/domain/somalier.py
  data_processors/pipeline/domain/somalier_check.py
  data_processors/pipeline/lambdas/orchestrator.py
  data_processors/pipeline/lambdas/somalier_check.py
  data_processors/pipeline/lambdas/somalier_extract.py
  data_processors/pipeline/lambdas/tests/test_somalier_check.py
  data_processors/pipeline/lambdas/tests/test_somalier_extract.py
  data_processors/pipeline/orchestration/somalier_extract_step.py
  data_processors/pipeline/orchestration/tests/test_somalier_extract_step.py
  data_processors/pipeline/orchestration/tests/test_tumor_normal_step.py
  data_processors/pipeline/services/somalier_check_srv.py
  data_processors/pipeline/tools/liborca.py
  data_processors/pipeline/tools/tests/test_liborca.py
  loaddata.sh
  serverless.yml
Labels: feature, epic, refactor

#461 Add run level skip list support
  data_processors/pipeline/lambdas/orchestrator.py
  data_processors/pipeline/lambdas/tests/test_orchestrator.py
  data_processors/pipeline/orchestration/tests/test_dragen_tso_ctdna_step.py
  data_processors/pipeline/orchestration/tests/test_dragen_wgs_qc_step.py
  data_processors/pipeline/orchestration/tests/test_tumor_normal_step.py
Labels: feature, change request
