Repository umccr/data-portal-apis, pull requests merged in 2022-02, with the labels that each got.

#400 Bumped dependencies
  README.md
  buildspec.yml
  package.json
  requirements.txt
  serverless.yml
  yarn.lock
Labels: dependencies

#402 Fixed unit test in PROD for step skip list using mockito spy
  data_processors/pipeline/orchestration/tests/test_dragen_tso_ctdna_step.py
  data_processors/pipeline/orchestration/tests/test_dragen_wgs_qc_step.py
  data_processors/pipeline/orchestration/tests/test_tumor_normal_step.py
Labels: fix

#403 Fixed unit test in PROD for step skip list using mockito spy
  data_processors/pipeline/orchestration/tests/test_dragen_tso_ctdna_step.py
  data_processors/pipeline/orchestration/tests/test_dragen_wgs_qc_step.py
  data_processors/pipeline/orchestration/tests/test_tumor_normal_step.py
Labels: fix

#407 Fixed LIMSRow update if there are existing record
  data_processors/pipeline/orchestration/google_lims_update_step.py
  data_processors/pipeline/orchestration/tests/test_google_lims_update_step.py
Labels: bug, fix

#408 Fixed BatchRule succeeded library run to be within Batch scope
  data_processors/pipeline/domain/batch.py
  data_processors/pipeline/orchestration/tests/test_dragen_tso_ctdna_step.py
  data_processors/pipeline/orchestration/tests/test_dragen_wgs_qc_step.py
Labels: bug, fix

#411 Import 2019 LabMetadata by default too
  data_processors/lims/lambdas/labmetadata.py
Labels: change request

#409 Added LabMetadata Sync API endpoint
  data_portal/serializers.py
  data_portal/urls.py
  data_portal/viewsets/labmetadata.py
  serverless.yml
  swagger/swagger.json
Labels: feature

#410 Make stringent LabMetadataRule check for workflow run
  data_processors/pipeline/domain/workflow.py
  data_processors/pipeline/orchestration/dragen_tso_ctdna_step.py
  data_processors/pipeline/orchestration/dragen_wgs_qc_step.py
  data_processors/pipeline/orchestration/dragen_wts_step.py
  data_processors/pipeline/orchestration/tests/test_dragen_tso_ctdna_step.py
  data_processors/pipeline/orchestration/tests/test_dragen_wgs_qc_step.py
  data_processors/pipeline/orchestration/tests/test_dragen_wts_step.py
Labels: bug, fix

#414 Pipeline SOP and Cleanup Ops
  docs/examples/fastq_lambda.R
  docs/pipeline/README.md
  docs/pipeline/automation.md
  docs/pipeline/bssh_sqs_event_replay.json
  docs/pipeline/cleanup/README.md
  docs/pipeline/cleanup/cleanup-analysis.sql
  docs/pipeline/cleanup/cleanup.sql
  docs/pipeline/misc-portal-lambda.md
Labels: documentation

#416 Update cleanup documentation
  docs/pipeline/README.md
  docs/pipeline/cleanup/README.md
Labels: documentation
