Repository umccr/data-portal-apis, pull requests merged in 2022-01, with the labels that each got.

#379 Added support for lab metadata sheet 2022
  data_processors/lims/lambdas/labmetadata.py
  data_processors/lims/lambdas/tests/test_labmetadata.py
Labels: change request

#380 Restore ICA Pipeline to normal Ops
  data_processors/pipeline/lambdas/orchestrator.py
  data_processors/pipeline/lambdas/tests/test_sqs_iap_event.py
  data_processors/pipeline/orchestration/tests/test_dragen_wgs_qc_step.py
  data_processors/pipeline/orchestration/tests/test_tumor_normal_step.py
Labels: change request

#378 Support IAM access to APIs
  data_portal/urls.py
  serverless.yml
Labels: feature, change request

#388 Added ICA pipeline emergency stop and configurable steps
  data_processors/pipeline/domain/tests/test_workflow.py
  data_processors/pipeline/domain/workflow.py
  data_processors/pipeline/lambdas/orchestrator.py
  data_processors/pipeline/lambdas/sqs_iap_event.py
  data_processors/pipeline/lambdas/tests/test_sqs_iap_event.py
  data_processors/pipeline/services/libraryrun_srv.py
  data_processors/pipeline/services/tests/test_libraryrun_srv.py
Labels: feature, change request

#389 Bumped Django4 and all dependencies
  data_portal/urls.py
  package.json
  requirements-dev.txt
  requirements-test.txt
  requirements.txt
  yarn.lock
Labels: dependencies

#390 Fixed build issue with sls domain manager
  data_portal/settings/aws.py
  package.json
  yarn.lock
Labels: dependencies, cicd, fix

#391 Fixed pipeline emergency stop upon PendingAnalysis
  data_processors/pipeline/lambdas/sqs_iap_event.py
Labels: fix

#392 Added SQS event handler for umccrise queue and Lambda
  .husky/pre-commit
  package.json
  serverless.yml
  yarn.lock
Labels: dependencies, fix

#393 Updated umccrise Slack notification Sample display
  data_processors/pipeline/services/notification_srv.py
Labels: change request, fix

#398 Improved LIMS update process with no delay to show up in Portal
  data_processors/pipeline/orchestration/google_lims_update_step.py
  data_processors/pipeline/orchestration/tests/test_google_lims_update_step.py
Labels: fix

#396 Improved metadata parser on handling CRLF in cell
  data_processors/lims/lambdas/google_lims.py
  data_processors/lims/lambdas/tests/test_google_lims.py
  data_processors/lims/lambdas/tests/test_labmetadata.py
  data_processors/lims/services/google_lims_srv.py
  data_processors/lims/services/labmetadata_srv.py
  data_processors/pipeline/lambdas/tests/test_orchestrator.py
Labels: fix
