Repository umccr/data-portal-apis, pull requests merged in 2022-03, with the labels that each got.

#419 Removed squashed migrations
  data_portal/migrations/0001_initial.py
  data_portal/migrations/0002_auto_20190829_0112.py
  data_portal/migrations/0003_limsrow_notes.py
  data_portal/migrations/0004_auto_20190829_0117.py
  data_portal/migrations/0005_auto_20190926_0254.py
  data_portal/migrations/0006_auto_20191001_0625.py
  data_portal/migrations/0007_auto_20191002_0603.py
  data_portal/migrations/0008_auto_20191015_2337.py
  data_portal/migrations/0009_auto_20191016_0050.py
  data_portal/migrations/0010_auto_20200123_0644.py
  data_portal/migrations/0011_auto_20200123_0649.py
  data_portal/migrations/0012_auto_20200123_0655.py
  data_portal/migrations/0013_auto_20200123_0705.py
  data_portal/migrations/0014_gdsfile.py
  data_portal/migrations/0015_auto_20200416_0528.py
  data_portal/migrations/0016_sequencerun.py
  data_portal/migrations/0017_workflow.py
  data_portal/migrations/0018_auto_20201007_0602.py
  data_portal/migrations/0019_batchrun_notified.py
  data_portal/migrations/0020_fastqlistrow.py
  data_portal/migrations/0020_report.py
  data_portal/migrations/0021_auto_20210319_0057.py
  data_portal/migrations/0022_merge_20210411_0614.py
  data_portal/migrations/0023_auto_20210416_1254.py
  data_portal/migrations/0023_labmetadata.py
  data_portal/migrations/0024_auto_20210422_0634.py
  data_portal/migrations/0025_auto_20210427_0649.py
  data_portal/migrations/0026_auto_20210430_1053.py
  data_portal/migrations/0027_merge_0023_labmetadata_0026_auto_20210430_1053.py
  data_portal/migrations/0028_alter_labmetadata_id.py
  data_portal/migrations/0029_alter_report_type.py
  data_portal/migrations/0030_alter_report_type.py
  data_portal/migrations/0030_auto_20210621_0440.py
  data_portal/migrations/0031_alter_report_type.py
  data_portal/migrations/0032_merge_0030_auto_20210621_0440_0031_alter_report_type.py
  data_portal/migrations/0033_auto_20210928_0456.py
  data_portal/migrations/0034_sequence.py
  data_portal/migrations/0035_libraryrun.py
  data_portal/migrations/0036_libraryrun_workflows.py
  data_portal/migrations/0037_workflow_portal_run_id.py
Labels: refactor

#420 Added SequenceStatus Aborted status
  data_portal/migrations/0002_alter_sequence_status.py
  data_portal/models/sequence.py
  data_portal/models/tests/test_sequence.py
Labels: change request

#418 Added manops
  data_processors/pipeline/lambdas/manops.py
  data_processors/pipeline/lambdas/tests/test_manops.py
  data_processors/pipeline/orchestration/rnasum_step.py
  data_processors/pipeline/services/workflow_srv.py
  docs/pipeline/automation.md
  docs/pipeline/rnasum.md
  serverless.yml
Labels: feature

#421 Fixed RNAsum step skip unittest
  data_processors/pipeline/orchestration/tests/test_rnasum_step.py
Labels: fix

#422 Added examples for Portal APIs using IAM authz
  docs/README.md
  docs/examples/portal_api_sig4.R
  docs/examples/portal_api_sig4.js
  docs/examples/portal_api_sig4.py
  package.json
  yarn.lock
Labels: documentation

#423 Bumped libica 2.0.0
  package.json
  requirements-dev.txt
  requirements.txt
  yarn.lock
Labels: dependencies

#424 Added arriba directory changes to RNASum workflow
  data_processors/pipeline/lambdas/rnasum.py
  data_processors/pipeline/orchestration/rnasum_step.py
  data_processors/pipeline/tools/liborca.py
Labels: change request

#425 Fixed rnasum Lambda unittest for arriba directory input
  data_processors/pipeline/lambdas/rnasum.py
  data_processors/pipeline/lambdas/tests/test_rnasum.py
  data_processors/pipeline/tools/tests/test_liborca.py
Labels: change request

#426 Added more integration test case for rnasum step
  data_processors/pipeline/orchestration/tests/test_rnasum_step.py
  docs/pipeline/rnasum.md
Labels: fix

#428 DevSecOps: Migrated to pre-commit and detect-secret hook
  .husky/.gitignore
  .husky/pre-commit
  .pre-commit-config.yaml
  .secrets.baseline
  Makefile
  README.md
  data_portal/models/tests/test_s3object.py
  data_portal/settings/it.py
  data_processors/pipeline/lambdas/dragen_tso_ctdna.py
  data_processors/pipeline/lambdas/dragen_wgs_qc.py
  data_processors/pipeline/lambdas/dragen_wts.py
  data_processors/pipeline/lambdas/notification.py
  data_processors/pipeline/lambdas/rnasum.py
  data_processors/pipeline/lambdas/tests/test_dragen_tso_ctdna.py
  data_processors/pipeline/lambdas/tests/test_dragen_wgs_qc.py
  data_processors/pipeline/lambdas/tests/test_dragen_wts.py
  data_processors/pipeline/lambdas/tumor_normal.py
  data_processors/pipeline/lambdas/umccrise.py
  data_processors/pipeline/orchestration/tests/test_rnasum_step.py
  data_processors/reports/lambdas/report_event.py
  data_processors/reports/tests/test_report.py
  data_processors/s3/tests/test_s3_event.py
  docs/pipeline/bssh_sqs_event_replay.json
  package.json
  requirements-dev.txt
  yarn.lock
Labels: change request, fix

#429 Increased Lambda timeout on LabMetadata and LIMS sheets sync
  serverless.yml
Labels: fix

#430 Improved doco
  docs/README.md
  docs/pairing.json
  docs/pipeline/README.md
  docs/pipeline/automation/README.md
  docs/pipeline/automation/bssh_sqs_event_replay.json
  docs/pipeline/automation/rnasum.md
  docs/pipeline/metadata.md
  docs/pipeline/misc-portal-lambda.md
Labels: documentation

#432 Changed RNAsum auto step
  data_processors/pipeline/orchestration/rnasum_step.py
  data_processors/pipeline/orchestration/tests/test_rnasum_step.py
  docs/pipeline/automation/README.md
  docs/pipeline/automation/rnasum.md
Labels: change request
