Repository umccr/data-portal-apis, pull requests merged in 2022-04, with the labels that each got.

#436 Updated umccrise path to be subdirectory of umccrise output directory
  data_processors/pipeline/orchestration/__init__.py
  data_processors/pipeline/orchestration/rnasum_step.py
  data_processors/pipeline/orchestration/tests/test_rnasum_step.py
  data_processors/pipeline/tools/liborca.py
Labels: fix

#439 Set minimum adapter overlap to three for all bclconvert samplesheets
  data_processors/pipeline/lambdas/bcl_convert.py
  data_processors/pipeline/lambdas/tests/test_bcl_convert.py
Labels: change request, fix

#441 Bumped serverless and dev dependencies
  package.json
  yarn.lock
Labels: dependencies

#443 Drop adapters from 10X samples
  data_processors/pipeline/lambdas/bcl_convert.py
  data_processors/pipeline/lambdas/tests/test_bcl_convert.py
Labels: change request, fix

#445 Updated to address S3 event processing performance issue (#143)
  data_processors/const.py
  data_processors/s3/lambdas/s3_event.py
  data_processors/s3/services.py
  data_processors/s3/tests/test_s3_event.py
Labels: critical, change request, fix

#448 Reinstated S3 delete event processing (#143)
  data_processors/s3/services.py
  serverless.yml
Labels: fix

#449 Fixed pandas deprecated frame append (#434)
  data_processors/lims/lambdas/tests/test_labmetadata.py
  data_processors/pipeline/lambdas/bcl_convert.py
  data_processors/pipeline/lambdas/tests/test_bcl_convert.py
Labels: fix
