Repository umccr/data-portal-apis, pull requests merged in 2023-09, with the labels that each got.

#615 Refactored Workflow model unique key to portal_run_id
  data_portal/fields.py
  data_portal/migrations/0005_backfill_portal_run_id.py
  data_portal/migrations/0006_alter_workflow_unique_together.py
  data_portal/migrations/0007_alter_workflow_portal_run_id.py
  data_portal/migrations/0008_remove_workflow_sample_name.py
  data_portal/migrations/0009_alter_workflow_version_alter_workflow_wfl_id_and_more.py
  data_portal/models/tests/test_libraryrun.py
  data_portal/models/tests/test_workflow.py
  data_portal/models/workflow.py
  data_portal/tests/factories.py
  data_portal/viewsets/tests/test_libraryrun.py
  data_processors/pipeline/domain/tests/test_pairing.py
  data_processors/pipeline/lambdas/tests/test_notification.py
  data_processors/pipeline/orchestration/tests/test_google_lims_update_step.py
  data_processors/pipeline/orchestration/tests/test_tumor_normal_step.py
  data_processors/pipeline/services/tests/test_metadata_srv.py
Labels: refactor

#616 Star Alignment Automation
  data_processors/pipeline/domain/config.py
  data_processors/pipeline/domain/workflow.py
  data_processors/pipeline/lambdas/bcl_convert.py
  data_processors/pipeline/lambdas/orchestrator.py
  data_processors/pipeline/lambdas/star_alignment.py
  data_processors/pipeline/lambdas/tests/test_star_alignment.py
  data_processors/pipeline/orchestration/star_alignment_step.py
  data_processors/pipeline/orchestration/tests/test_star_alignment_step.py
  data_processors/pipeline/services/fastq_srv.py
  loaddata.sh
  serverless.yml
Labels: feature

#617 Refactored WorkflowHelper portal_run_id generator to use IdHelper
  data_processors/pipeline/domain/tests/test_workflow.py
  data_processors/pipeline/domain/workflow.py
Labels: refactor

#618 Implemented orchestrator NG handler
  data_portal/tests/factories.py
  data_processors/pipeline/domain/event/__init__.py
  data_processors/pipeline/domain/event/tests/__init__.py
  data_processors/pipeline/domain/event/tests/test_wrsc.py
  data_processors/pipeline/domain/event/wrsc.py
  data_processors/pipeline/domain/workflow.py
  data_processors/pipeline/lambdas/orchestrator.py
  data_processors/pipeline/lambdas/sqs_batch_event.py
  data_processors/pipeline/lambdas/tests/test_orchestrator.py
  data_processors/pipeline/lambdas/tests/test_sqs_batch_event.py
  data_processors/pipeline/lambdas/tests/test_workflow_update.py
  data_processors/pipeline/lambdas/workflow_update.py
  data_processors/pipeline/services/workflow_srv.py
  docs/schemas/README.md
  docs/schemas/WorkflowRunStateChange.schema.json
  requirements-dev.txt
  requirements.txt
  serverless.yml
Labels: feature, refactor
