Repository umccr/data-portal-apis, pull requests merged in 2023-03, with the labels that each got.

#571 DRAFT: Add support for filtering out metadata for libraries not sequenced yet
  data_portal/models/labmetadata.py
  data_portal/models/tests/test_labmetadata.py
Labels: fix

#573 Solved multiple WTS libraries by using latest to their sequencing time
  data_portal/tests/factories.py
  data_processors/pipeline/orchestration/rnasum_step.py
  data_processors/pipeline/orchestration/tests/test_rnasum_step.py
  data_processors/pipeline/services/metadata_srv.py
  data_processors/pipeline/services/tests/test_metadata_srv.py
Labels: change request

#572 Updated umccrise step to take germline as input rather than its own step
  data_processors/pipeline/lambdas/tests/test_tumor_normal.py
  data_processors/pipeline/lambdas/tests/test_umccrise.py
  data_processors/pipeline/lambdas/tumor_normal.py
  data_processors/pipeline/lambdas/umccrise.py
  data_processors/pipeline/orchestration/tests/test_tumor_normal_step.py
  data_processors/pipeline/orchestration/tests/test_umccrise_step.py
  data_processors/pipeline/orchestration/tumor_normal_step.py
  data_processors/pipeline/orchestration/umccrise_step.py
  data_processors/pipeline/tools/liborca.py
  data_processors/pipeline/tools/tests/test_liborca.py
  docs/pipeline/automation/tumor_normal.md
  docs/pipeline/automation/tumor_normal_payload.json
  docs/pipeline/automation/umccrise.md
  docs/pipeline/automation/umccrise_payload.json
Labels: change request

#574 Fixed tumor normal and RNAsum to use sequenced only library
  data_processors/pipeline/orchestration/tests/test_rnasum_step.py
  data_processors/pipeline/orchestration/tests/test_tumor_normal_step.py
  data_processors/pipeline/orchestration/tumor_normal_step.py
  data_processors/pipeline/services/metadata_srv.py
  data_processors/pipeline/services/tests/test_metadata_srv.py
Labels: bug, fix

#575 Fixed pairing endpoint to use sequenced only library
  data_processors/pipeline/domain/pairing.py
  data_processors/pipeline/services/metadata_srv.py
  data_processors/pipeline/services/tests/test_metadata_srv.py
Labels: bug, fix

#576 Added example for GDS folders bundler and downloader scripts
  docs/examples/gds_bundle/.gitignore
  docs/examples/gds_bundle/README.md
  docs/examples/gds_bundle/gds_folders.txt
  docs/examples/gds_bundle/gen_bundle.sh
  docs/examples/gds_bundle/gen_downloader.sh
Labels: documentation

#577 Improved gds bundler README and fixed minor typo
  docs/examples/gds_bundle/README.md
  docs/examples/gds_bundle/gds_folders.txt
  docs/examples/gds_bundle/gen_bundle.sh
Labels: documentation

#578 Update umccrise output directory key
  data_processors/pipeline/orchestration/tests/test_rnasum_step.py
  data_processors/pipeline/tools/liborca.py
  data_processors/pipeline/tools/tests/test_liborca.py
Labels: bug

#579 Added TSO tsv output in Subject analysis summary
  data_portal/models/gdsfile.py
Labels: change request

#581 Fixed GDS PreSigned URL Override to allow opening report in inline browser tab
  data_portal/viewsets/gdsfile.py
  requirements.txt
Labels: fix
