Repository umccr/data-portal-apis, pull requests merged in 2023-08, with the labels that each got.

#608 Fixed models import from Python package
  data_portal/models/__init__.py
Labels: fix

#607 Fixed unittest for orchestration WTS step changes
  data_processors/pipeline/orchestration/dragen_wts_step.py
  data_processors/pipeline/orchestration/tests/test_dragen_wts_step.py
Labels: fix

#597 Run QC for WTS alongside WGS
  data_portal/tests/factories.py
  data_portal/viewsets/tests/test_libraryrun.py
  data_processors/pipeline/domain/tests/test_pairing.py
  data_processors/pipeline/domain/workflow.py
  data_processors/pipeline/lambdas/dragen_wgs_qc.py
  data_processors/pipeline/lambdas/dragen_wts.py
  data_processors/pipeline/lambdas/orchestrator.py
  data_processors/pipeline/lambdas/tests/test_dragen_wgs_qc.py
  data_processors/pipeline/lambdas/tests/test_dragen_wts.py
  data_processors/pipeline/lambdas/tests/test_orchestrator.py
  data_processors/pipeline/lambdas/tests/test_sqs_iap_event.py
  data_processors/pipeline/orchestration/__init__.py
  data_processors/pipeline/orchestration/dragen_wgs_qc_step.py
  data_processors/pipeline/orchestration/dragen_wts_step.py
  data_processors/pipeline/orchestration/tests/test_dragen_wgs_qc_step.py
  data_processors/pipeline/orchestration/tests/test_dragen_wts_step.py
  data_processors/pipeline/orchestration/tests/test_tumor_normal_step.py
  data_processors/pipeline/orchestration/tumor_normal_step.py
  data_processors/pipeline/services/metadata_srv.py
  data_processors/pipeline/services/tests/test_metadata_srv.py
Labels: feature

#609 Improved FastqListRow lookup filter by specific SequenceRun instance
  data_processors/pipeline/domain/batch.py
  data_processors/pipeline/domain/tests/test_batch.py
  data_processors/pipeline/services/fastq_srv.py
  data_processors/pipeline/services/tests/test_fastq_srv.py
Labels: bug, fix

#611 Handle differing workflow parameters between wts qc and wgs qc
  data_processors/pipeline/lambdas/dragen_wgs_qc.py
Labels: bug, fix

#612 Updated Portal metadata documentation
  docs/pipeline/metadata.md
Labels: documentation

#595 Started fixing discovery of holmes endpoints
  data_processors/pipeline/domain/somalier.py
  data_processors/pipeline/lambdas/somalier_check.py
  data_processors/pipeline/lambdas/somalier_extract.py
  data_processors/pipeline/lambdas/tests/test_somalier_check.py
  data_processors/pipeline/lambdas/tests/test_somalier_extract.py
  docs/pipeline/automation/README.md
  serverless.yml
Labels: change request, fix

#613 Improved DRAGEN Alignment QC impl
  data_processors/pipeline/domain/workflow.py
  data_processors/pipeline/lambdas/dragen_wgs_qc.py
  data_processors/pipeline/lambdas/orchestrator.py
  data_processors/pipeline/orchestration/dragen_wgs_qc_step.py
  data_processors/pipeline/orchestration/somalier_extract_step.py
  data_processors/pipeline/tools/liborca.py
  data_processors/pipeline/tools/tests/test_liborca.py
Labels: documentation, fix

#614 Added drawio doc around Portal Automation architecture
  docs/model/architecture_code_design.drawio
  docs/model/architecture_code_design.pdf
Labels: documentation
