Repository umccr/data-portal-apis, pull requests merged in 2023-11, with the labels that each got.

#641 Rollback SQS Standard queue event router handler behaviour
  data_processors/pipeline/lambdas/sqs_batch_event.py
  data_processors/pipeline/lambdas/sqs_iap_event.py
  data_processors/pipeline/lambdas/tests/test_sqs_batch_event.py
  data_processors/pipeline/lambdas/tests/test_sqs_iap_event.py
  serverless.yml
Labels: fix

#643 Bumped dependencies
  package.json
  requirements.txt
  yarn.lock
Labels: dependencies

#645 Bumped dependencies
  buildspec.yml
  package.json
  yarn.lock
Labels: dependencies

#648 Updated documentation
  .gitignore
  Makefile
  README.md
  docker-compose.ci.yml
  docker-compose.yml
  docs/ENDPOINTS.md
  docs/PORTAL_IAM.md
  docs/PORTAL_RELEASE.md
  docs/PORTAL_TOKEN.md
  docs/README.md
  docs/model/automated_pipeline.drawio
  docs/model/automated_pipeline.png
  docs/pipeline/README.md
  docs/pipeline/automation/README.md
  docs/pipeline/automation/oncoanalyser_wgs.md
  docs/pipeline/automation/oncoanalyser_wgs_payload.json
  docs/pipeline/automation/oncoanalyser_wts.md
  docs/pipeline/automation/oncoanalyser_wts_payload.json
  docs/pipeline/automation/rnasum.md
  docs/pipeline/automation/star_alignment.md
  docs/pipeline/automation/star_alignment_payload.json
  docs/pipeline/automation/transcriptome.md
  docs/pipeline/automation/transcriptome_payload.json
  docs/pipeline/automation/tso_ctdna.md
  docs/pipeline/automation/tso_ctdna_payload.json
  docs/pipeline/automation/tumor_normal.md
  docs/pipeline/automation/umccrise.md
  docs/pipeline/metadata.md
  requirements-dev.txt
  swagger/README.md
  swagger/console.json
  swagger/gds.json
  swagger/openapi_public.yaml
  swagger/swagger.json
  swagger/tes.json
Labels: documentation

#649 Updated PORTAL_RELEASE.md documentation
  docs/PORTAL_RELEASE.md
Labels: documentation

#650 Improved TSO ctDNA Lambda handler
  data_processors/pipeline/lambdas/dragen_tso_ctdna.py
  data_processors/pipeline/lambdas/star_alignment.py
  data_processors/pipeline/orchestration/tests/test_dragen_tso_ctdna_step.py
  data_processors/pipeline/orchestration/tests/test_dragen_wgs_qc_step.py
  data_processors/pipeline/services/libraryrun_srv.py
  docs/pipeline/automation/tso_ctdna.md
  docs/pipeline/automation/tso_ctdna_payload.json
Labels: fix

#651 Improved WorkflowRunStateChange schema for usabiliy
  data_processors/pipeline/domain/event/wrsc.py
  data_processors/pipeline/lambdas/tests/test_workflow_update.py
  data_processors/pipeline/lambdas/workflow_update.py
  docs/schemas/WorkflowRunStateChange.schema.json
Labels: change request
