Repository umccr/data-portal-apis, pull requests merged in 2023-02, with the labels that each got.

#546 Bumped dependencies
  package.json
  requirements-dev.txt
  requirements.txt
  yarn.lock
Labels: dependencies

#549 Updated swagger and endpoints doc
  docs/ENDPOINTS.md
  swagger/swagger.json
Labels: documentation

#550 Updated doc new base domain endpoint
  data_processors/pipeline/orchestration/tests/test_rnasum_step.py
  docs/ENDPOINTS.md
  docs/README.md
  docs/athena/pairing.sql
  docs/examples/fastq_list_row.R
  docs/examples/fastq_presigned.R
  docs/examples/fastq_simple_list.R
  docs/examples/gds_dl_gen.sh
  docs/examples/kallisto.sh
  docs/examples/pairing_tn_fastq.R
  docs/examples/portal_api_sig4.R
  docs/examples/portal_api_sig4.js
  docs/examples/portal_api_sig4.py
Labels: documentation

#554 `/fastq` API Additional filters
  data_portal/models/fastqlistrow.py
  data_portal/models/tests/test_fastqlistrow.py
Labels: change request

#556 Accept `Content-Disposition` as header in GDS presign
  data_portal/viewsets/gdsfile.py
  requirements.txt
Labels: feature

#557 Allow `Content-Disposition` in CORS
  data_portal/settings/base.py
Labels: change request

#560 Deprecated manops domain and endpoint
  data_portal/tests/factories.py
  data_portal/urls/base.py
  data_portal/viewsets/manops.py
  data_portal/viewsets/tests/test_manops.py
  data_processors/pipeline/domain/manops.py
  data_processors/pipeline/domain/tests/test_manops.py
  data_processors/pipeline/lambdas/manops.py
  data_processors/pipeline/lambdas/rnasum.py
  data_processors/pipeline/lambdas/tests/test_manops.py
  data_processors/pipeline/lambdas/tests/test_rnasum.py
  data_processors/pipeline/orchestration/tests/test_rnasum_step.py
  docs/pipeline/automation/rnasum.md
  serverless.yml
  swagger/swagger.json
Labels: refactor

#570 Update API-gateway Serverless CORS
  serverless.yml
Labels: fix

#565 Added workDirectory to primary data helper
  data_processors/pipeline/domain/tests/test_workflow.py
  data_processors/pipeline/domain/workflow.py
Labels: feature

#569 Cleaned up loaddata script
  loaddata.sh
Labels: bug, fix

#567 Fix: 561 - ctTSO NTC should be run
  data_processors/pipeline/domain/workflow.py
  data_processors/pipeline/orchestration/dragen_tso_ctdna_step.py
  data_processors/pipeline/orchestration/tests/test_dragen_tso_ctdna_step.py
Labels: change request

#566 Added support for TSO BAM fingerprinting through Holmes
  data_portal/urls/base.py
  data_portal/viewsets/somalier.py
  data_processors/pipeline/domain/somalier.py
  data_processors/pipeline/domain/tests/test_somalier.py
  data_processors/pipeline/lambdas/orchestrator.py
  data_processors/pipeline/lambdas/somalier_check.py
  data_processors/pipeline/lambdas/somalier_extract.py
  data_processors/pipeline/lambdas/tests/test_somalier_check.py
  data_processors/pipeline/lambdas/tests/test_somalier_extract.py
  data_processors/pipeline/orchestration/somalier_extract_step.py
  data_processors/pipeline/orchestration/tests/test_somalier_extract_step.py
  docs/ENDPOINTS.md
  docs/pipeline/automation/README.md
  swagger/swagger.json
Labels: feature
