Repository umccr/data-portal-apis, pull requests merged in 2023-10, with the labels that each got.

#619 Implemented oncoanalyser wts automation
  data_portal/tests/factories.py
  data_processors/pipeline/domain/config.py
  data_processors/pipeline/domain/workflow.py
  data_processors/pipeline/lambdas/oncoanalyser_wts.py
  data_processors/pipeline/lambdas/orchestrator.py
  data_processors/pipeline/lambdas/tests/test_oncoanalyser_wts.py
  data_processors/pipeline/orchestration/oncoanalyser_wts_step.py
  data_processors/pipeline/orchestration/tests/test_oncoanalyser_wts_step.py
  data_processors/pipeline/services/s3object_srv.py
  data_processors/pipeline/services/tests/test_s3object_srv.py
  loaddata.sh
  serverless.yml
Labels: feature

#620 Fastq list rows are now inside the tso500_sample configuration for cttso
  data_processors/pipeline/lambdas/dragen_tso_ctdna.py
  data_processors/pipeline/lambdas/tests/test_dragen_tso_ctdna.py
  data_processors/pipeline/orchestration/dragen_tso_ctdna_step.py
Labels: change request

#622 Added code coverage to toolchain
  .coveragerc
  .gitignore
  Makefile
  requirements-test.txt
Labels: devops

#623 Implemented automation for oncoanalyser wgts existing both
  data_portal/tests/factories.py
  data_processors/pipeline/domain/config.py
  data_processors/pipeline/domain/workflow.py
  data_processors/pipeline/lambdas/oncoanalyser_wgts_existing_both.py
  data_processors/pipeline/lambdas/orchestrator.py
  data_processors/pipeline/lambdas/tests/test_oncoanalyser_wgts_existing_both.py
  data_processors/pipeline/lambdas/tests/test_sqs_batch_event.py
  data_processors/pipeline/lambdas/tests/test_workflow_update.py
  data_processors/pipeline/orchestration/oncoanalyser_wgs_step.py
  data_processors/pipeline/orchestration/oncoanalyser_wgts_existing_both_step.py
  data_processors/pipeline/orchestration/oncoanalyser_wts_step.py
  data_processors/pipeline/orchestration/tests/test_oncoanalyser_wgts_existing_both_step.py
  data_processors/pipeline/services/s3object_srv.py
  data_processors/pipeline/services/tests/test_s3object_srv.py
  loaddata.sh
  serverless.yml
Labels: feature

#624 Upgraded Portal backend to Python3.11 and Node18
  README.md
  buildspec.yml
  serverless.yml
Labels: dependencies

#625 Fixed CodeBuild to use localised yarn with npx
  buildspec.yml
Labels: cicd

#627 Bumped dependencies
  package.json
  requirements-dev.txt
  requirements-test.txt
  requirements.txt
  yarn.lock
Labels: dependencies

#628 Fixed serverless long Lambda name
  serverless.yml
Labels: fix

#629 Removed serverless domain manager stage variable
  buildspec.yml
  serverless.yml
Labels: fix

#631 Removed transcriptome BAM fingerprinting from orchestrator
  data_processors/pipeline/lambdas/orchestrator.py
  data_processors/pipeline/orchestration/somalier_extract_step.py
Labels: change request

#633 Improved QC implementation and reinforced unit testing
  data_processors/pipeline/domain/tests/test_workflow.py
  data_processors/pipeline/domain/workflow.py
  data_processors/pipeline/lambdas/dragen_wgs_qc.py
  data_processors/pipeline/lambdas/tests/test_dragen_wgs_qc.py
  data_processors/pipeline/orchestration/tests/test_dragen_wgs_qc_step.py
  data_processors/pipeline/services/notification_srv.py
Labels: fix

#632 Improved SQS Lambda handler partial batch responses - ReportBatchItemFailures
  data_processors/pipeline/domain/tests/test_workflow.py
  data_processors/pipeline/domain/workflow.py
  data_processors/pipeline/lambdas/dragen_tso_ctdna.py
  data_processors/pipeline/lambdas/dragen_wgs_qc.py
  data_processors/pipeline/lambdas/dragen_wts.py
  data_processors/pipeline/lambdas/notification.py
  data_processors/pipeline/lambdas/oncoanalyser_wgs.py
  data_processors/pipeline/lambdas/oncoanalyser_wgts_existing_both.py
  data_processors/pipeline/lambdas/oncoanalyser_wts.py
  data_processors/pipeline/lambdas/rnasum.py
  data_processors/pipeline/lambdas/sash.py
  data_processors/pipeline/lambdas/somalier_extract.py
  data_processors/pipeline/lambdas/star_alignment.py
  data_processors/pipeline/lambdas/tests/test_dragen_tso_ctdna.py
  data_processors/pipeline/lambdas/tests/test_dragen_wgs_qc.py
  data_processors/pipeline/lambdas/tests/test_dragen_wts.py
  data_processors/pipeline/lambdas/tumor_normal.py
  data_processors/pipeline/lambdas/umccrise.py
  data_processors/pipeline/orchestration/tests/test_dragen_wgs_qc_step.py
  data_processors/pipeline/services/notification_srv.py
  serverless.yml
Labels: fix

#634 Improved ICA ENS and AWS Batch SQS Lambda handlers response in dict
  data_processors/pipeline/lambdas/sqs_batch_event.py
  data_processors/pipeline/lambdas/sqs_iap_event.py
  data_processors/pipeline/lambdas/tests/test_sqs_batch_event.py
  data_processors/pipeline/lambdas/tests/test_sqs_iap_event.py
Labels: fix

#635 Fixed QC workflow trigger wrong workflow typing
  data_processors/pipeline/lambdas/dragen_wgs_qc.py
  data_processors/pipeline/lambdas/tests/test_dragen_wgs_qc.py
Labels: bug, fix

#636 Improved star alignment step implementation
  data_portal/tests/factories.py
  data_processors/pipeline/orchestration/star_alignment_step.py
  data_processors/pipeline/orchestration/tests/test_star_alignment_step.py
  data_processors/pipeline/services/metadata_srv.py
Labels: fix

#637 Disabled ReportBatchItemFailures response for SQS Standard queue
  data_processors/pipeline/lambdas/sqs_batch_event.py
  data_processors/pipeline/lambdas/sqs_iap_event.py
Labels: fix

#638 Improved workflow service layer running workflow lookup
  data_portal/models/workflow.py
  data_processors/pipeline/services/tests/test_workflow_srv.py
  data_processors/pipeline/services/workflow_srv.py
Labels: fix

#640 Bumped dependencies
  requirements.txt
Labels: dependencies
