Repository umccr/data-portal-apis, pull requests merged in 2024-05, with the labels that each got.

#670 Fix: Running local docker-compose.yml
  docker-compose.yml
Labels: cicd

#675 Fixed docker compose mysql-8.4 for CodeBuild CI
  docker-compose.ci.yml
  docker-compose.yml
Labels: dependencies, cicd, fix

#677 PRID typos
  docs/pipeline/portal_run_id.md
Labels: documentation

#676 Fixed and pinned docker compose mysql-8.0 for CodeBuild CI and local dev
  docker-compose.ci.yml
  docker-compose.override.sample.yml
  docker-compose.yml
Labels: cicd, fix

#669 Added Portal Run ID documentation
  docs/model/portal_run_id.png
  docs/pipeline/README.md
  docs/pipeline/portal_run_id.md
Labels: documentation

#679 Added test case to debug & verify wgs rerun lib skip auto-pairing
  data_processors/pipeline/orchestration/tests/test_tumor_normal_step.py
Labels: documentation, investigation

#680 Improved RNAsum v1 input keys test cases
  data_processors/pipeline/lambdas/rnasum.py
  data_processors/pipeline/lambdas/tests/test_rnasum.py
  data_processors/pipeline/orchestration/tests/test_rnasum_step.py
Labels: change request

#674 Update RNAsum orchestration
  data_processors/pipeline/lambdas/rnasum.py
  data_processors/pipeline/lambdas/tests/test_rnasum.py
  data_processors/pipeline/orchestration/rnasum_step.py
  data_processors/pipeline/orchestration/tests/test_rnasum_step.py
  docs/pipeline/automation/rnasum.md
Labels: change request

#681 Added ggshield config
  .gitguardian.yaml
  .pre-commit-config.yaml
Labels: documentation, devops

#682 Fixed BSSH mock event generator script
  docs/pipeline/automation/bssh_sqs_event_replay.py
Labels: documentation, fix

#683 Upgraded to yarn-4.2.2
  .gitattributes
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarn/releases/yarn-3.5.1.cjs
  .yarn/releases/yarn-4.2.2.cjs
  .yarnrc.yml
  README.md
  package.json
  yarn.lock
Labels: dependencies

#687 Fix/security issue fix from dependabot alerts
  requirements.txt
  yarn.lock
Labels: dependencies
