Repository umccr/data-portal-apis, pull requests merged in 2024-11, with the labels that each got.

#734 Removed deprecated client domains and ssm param
  data_portal/settings/aws.py
  serverless.yml
Labels: change request, fix

#735 Feat: Extend Presign URL Expiry
  data_portal/viewsets/presignedurl.py
  data_portal/viewsets/s3object.py
  data_portal/viewsets/utils.py
  requirements.txt
Labels: feature

#736 Implemented AnalysisResult index model
  data_portal/management/commands/resultcrawler.py
  data_portal/migrations/0012_analysisresult.py
  data_portal/models/__init__.py
  data_portal/models/analysisresult.py
  data_portal/viewsets/subject.py
  data_processors/s3/tests/test_s3_event.py
Labels: feature, migration
