Repository umccr/data-portal-apis, pull requests merged in 2024-01, with the labels that each got.

#653 Add support for lab metadata tracking sheet 2024
  data_portal/serializers.py
  data_processors/lims/lambdas/labmetadata.py
  data_processors/lims/lambdas/tests/test_labmetadata.py
Labels: change request

#659 Add `results_sash` in subject API
  data_portal/models/s3object.py
  data_portal/models/tests/test_s3object.py
  data_portal/viewsets/subject.py
Labels: change request

#656 Fixed transcriptome orchestration step skip if FastqListRow empty
  data_processors/pipeline/orchestration/dragen_wts_step.py
  data_processors/pipeline/orchestration/tests/test_dragen_wts_step.py
Labels: fix

#657 Improved Pipeline Automation documentation
  docs/pipeline/README.md
  docs/pipeline/automation/README.md
  docs/pipeline/automation/transcriptome.md
  docs/pipeline/automation/tso_ctdna.md
  docs/pipeline/automation/tumor_normal.md
  docs/pipeline/metadata.md
Labels: documentation

#658 Bumped dependencies
  package.json
  yarn.lock
Labels: dependencies

#660 Refine filter on get `sash_results`
  data_portal/models/s3object.py
  data_portal/models/tests/test_s3object.py
Labels: change request
