Repository umccr/data-portal-apis, pull requests merged in 2024-06, with the labels that each got.

#689 replace status page domain name
  serverless.yml
Labels: change request

#690 Added Portal LabMetadata LibraryID suffix annotation treatment
  data_processors/pipeline/orchestration/oncoanalyser_wgts_existing_both_step.py
  docs/pipeline/README.md
  docs/pipeline/automation/tumor_normal.md
  docs/pipeline/cleanup/README.md
  docs/pipeline/cleanup/cleanup-analysis.sql
  docs/pipeline/cleanup/cleanup.sql
  docs/pipeline/library_suffix.md
  docs/pipeline/metadata.md
Labels: documentation

#692 Added documentation on how to trigger DRAGEN Alignment QC
  docs/pipeline/automation/README.md
  docs/pipeline/automation/dragen_alignment_qc.json
  docs/pipeline/automation/dragen_alignment_qc.md
Labels: documentation

#693 Added Tumor Normal engineParameter override for tesUseInputManifest never
  data_processors/pipeline/domain/tests/test_workflow.py
  data_processors/pipeline/domain/workflow.py
Labels: change request, fix

#695 Updated LabMetadata model enum for assay, type, source
  data_portal/models/labmetadata.py
Labels: change request

#696 Added support for EventBridge S3 event processing
  data_processors/s3/lambdas/s3_event.py
  data_processors/s3/services.py
  data_processors/s3/tests/test_s3_event.py
Labels: change request

#697 Updated doc for WTS sample with multiple lane FASTQs
  docs/pipeline/automation/star_alignment.md
  docs/pipeline/automation/transcriptome.md
  docs/pipeline/library_suffix.md
Labels: documentation

#698 Updated LabMetadata model enum for assay, type, source - migration script
  data_portal/migrations/0010_alter_labmetadata_assay_alter_labmetadata_quality_and_more.py
Labels: change request

#700 Fixed pandas dataframe applymap future warning
  data_processors/lims/services/google_lims_srv.py
  data_processors/lims/services/labmetadata_srv.py
  loaddata.sh
  requirements.txt
Labels: dependencies, fix
